# Generated by Django 3.2.5 on 2021-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_bid', models.IntegerField()),
                ('listing_id', models.IntegerField()),
                ('title', models.CharField(max_length=16)),
                ('user', models.CharField(max_length=32)),
            ],
        ),
    ]
