# Generated by Django 3.2.5 on 2021-08-29 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connections',
            name='followers',
            field=models.ManyToManyField(related_name='followers_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connections',
            name='following',
            field=models.ManyToManyField(related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
