# Generated by Django 3.2.5 on 2021-08-30 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210829_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='followers',
            field=models.ManyToManyField(default=None, related_name='followers_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connections',
            name='following',
            field=models.ManyToManyField(default=None, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
